### ISSUE TITLE
Add an emacs HOWTO

### ISSUE THREAD

**Issue by termlen0** [abo-abo/gtk-pomodoro-indicator#1]
I installed the package from melpa, but cant find any info on how to invoke it within org-mode. Any help to hook it up with org-pomodoro ? That way, when I am on a task and M-x org-pomodoro, it will also start the clock?

**Comment by abo-abo** [comment]
Thanks, please test:

```elisp
;; integrate with `org-pomodoro'
(gpi-setup)
```
