### ISSUE TITLE
pomodoro_indicator directory not included in Melpa install

### ISSUE THREAD

**Issue by felipeochoa** [abo-abo/gtk-pomodoro-indicator#2]
This results in

> python: can't open file '/path/to/.emacs.d/elpa/gtk-pomodoro-indicator-20171230.840/pomodoro_indicator/pomodoro_indicator.py': [Errno 2] No such file or directory

You can verify the missing directory here: https://melpa.org/packages/gtk-pomodoro-indicator-20171230.840.tar

**Comment by abo-abo** [comment]
Thanks, I'll make a PR to MELPA to fix this.

**Comment by abo-abo** [comment]
Thanks, should be fixed now.
