### ISSUE TITLE
Incomplete output in Py3status

### ISSUE THREAD

**Issue by ertwro** [abo-abo/gtk-pomodoro-indicator#3]
Hi. While I know GPI is intended for use with GTK-based bars and it works well in them (tried it with mate-panel and was perfect), but I tried a more minimalist bar with i3. In Py3status, the SVG icon loads. If I click it, it displays the quit menu in the bar, it even disappears on its own after the time is up and the coffee break appears, but the text doesn't appear, no matter what. I've reinstalled gi in python and installed indicator-kdeconnect but without luck. The Py3status Syslog file doesn't even register GPI. So maybe you could indicate me how better debug or something that would be awesome. I miss this feature. On the emacs side, everything works, as always.
[backtrace.txt](https://github.com/abo-abo/gtk-pomodoro-indicator/files/2707479/backtrace.txt)

**Comment by abo-abo** [comment]
Sorry, no idea. I had a similar problem with Cinnamon: the icon is visible, but there is no text.

You can try to report this issue for `gi.repository.AppIndicator3`, since that's what I'm using here.

**Comment by ertwro** [comment]
Thank you and again your packages are awesome.
